
services:
  todo-service:
    build:
      context: ./todo-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - ./todo-service/.env.docker
    volumes:
      - todo-data:/app/data
    networks:
      - todo-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - PORT=3002
      - TODO_SERVICE_URL=http://todo-service:3001
    depends_on:
      - todo-service
    networks:
      - todo-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  todo-data:

networks:
  todo-network:
    driver: bridge
